#50 Asyncapi support external files
corunet/scc-multiapi-converter pull request #52
Opened 2022-06-21 13:40 UTC by jmejutovazquez

Closes #50

2022-06-21 14:24 UTC, jemacineiras approved these changes

2022-06-21 14:42 UTC, fcampostato submitted a review, later dismissed

2022-07-01 11:24 UTC, Rivarsal approved these changes

2022-07-04 07:13 UTC, jemacineiras requested changes
Please review the code again.

2022-07-05 17:29 UTC, jmejutovazquez commented on src/main/java/net/coru/multiapi/converter/asyncapi/AsyncApiContractConverter.java
> +    Map<String, Object> messageBody = new HashMap<>();
Of course, thanks.

2022-07-05 17:30 UTC, jmejutovazquez commented on src/main/java/net/coru/multiapi/converter/asyncapi/AsyncApiContractConverter.java
> +    Map<String, Object> internalMessageBody = messageBody;
Checked and fixed, thanks.

2022-07-11 08:50 UTC, Rivarsal approved these changes

2022-07-12 16:09 UTC, fcampostato approved these changes

2022-07-13 14:22 UTC, merged