Fix behavior for array of refs
corunet/scc-multiapi-converter pull request #55
Opened 2022-07-05 16:00 UTC by fcampostato

Closes #54

2022-07-06 15:23 UTC, jemacineiras submitted a review, later dismissed

2022-07-06 15:33 UTC, jmejutovazquez submitted a review, later dismissed

2022-07-11 08:49 UTC, Rivarsal approved these changes

2022-07-12 15:15 UTC, Rivarsal requested changes
We have to doublecheck what is being generated in the array of refs. Currently is not okay

2022-07-14 08:00 UTC, jmejutovazquez approved these changes

2022-07-14 15:28 UTC, Rivarsal approved these changes

2022-07-14 15:52 UTC, Rivarsal submitted a review, later dismissed

2022-07-15 07:48 UTC, jmejutovazquez approved these changes

2022-07-18 09:57 UTC, jmejutovazquez approved these changes

2022-07-18 10:00 UTC, merged